import type {Metadata, Viewport} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react"

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    manifest: "/manifest.json",
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const viewport: Viewport = {
    themeColor: "#FFFFFF",
};
export default function RootLayout({ children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
    )
}
